### PR TITLE
[WIP] Fixes typos

### PR DESCRIPTION
**Pull request by abhi18av**
Nothing major in this PR.

### CODE REVIEW

**Comment by awkay** [comment]
Could you combine "boy scouting" fixes like this with larger PRs?  I don't like to have commits peppered everywhere with one-line changes :)

**Comment by abhi18av** [comment]
😄 "boy scouting", aye aye captain - will keep this in mind!

**Comment by awkay** [comment]
Let's move this fix to the config branch...just re-make the change there and let's close this one.

**Comment by abhi18av** [comment]
Okay, noted.

**Pull request closed without merging**
